name: Package Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Profiles
        run: mvn -B package --file pom.xml -P linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-application
          path: target/*.jar
          if-no-files-found: error